[filter]
players = "鹿目円"  # 需要分析的玩家昵称
levels = ["四般東喰赤", "四般南喰赤", "四上南喰赤"]  # 需要分析的牌桌级别
timeafter = "1970-01-01 08:00:00"  # 分析起始时间
timebefore = "2099-12-31 23:59:59"  # 分析截止时间
paipu_txt = "牌谱.txt"  # 保存牌谱的文件名
